---
title: "Making continuous assessment work"
description: "How to do better at teaching without driving everyone crazy. Maybe."
author: "Toby Driscoll"
date: "7/13/2015"
categories:
  - math
  - teaching
---

I’ve come to think that in math at least, continuous learning and assessment may be more important even than [active learning](http://www.crlt.umich.edu/tstrategies/tsal). The traditional model of chunking assessments into weekly or monthly batches encourages the cram-and-dump style of “learning.” Since students are allowed to delay work on assignments that are crucial to their understanding of incoming material, it’s impossible for them to build that understanding in real time. Instead they copy and hope to parse later, when assessment is demanded.

It’s tempting to say that students should suck it up and organize their time better. This attitude ignores human nature, especially the nature of people in late adolescence and early adulthood. Even a large part of my own work is deadline-driven rather than proactive. And I love math!

Any big change in expectations encounters resistance. Fortunately, breaking through that resistance sometimes spills over into breaking resistance to the tough job of learning itself.  The trick is doing so in a way that feels fair to the students and manageable to the instructor. It’s hard to overthrow everything at once.

Here’s what I’m thinking for my fall course on numerical computing. Each class meeting (3 times a week) has a cycle associated with it:

Before class:

- (them) Read/watch and reflect.
- (them) Take an online quiz on the new material.

In class:

- (mostly me) Review problem spots. Fill in some of the details.
- (us) Work to produce one graph or one table relevant to the new material. 
- (them) Turn in a description of what is still not clear.

After class: 

- (me) While everything is fresh, I take one last try at explaining material that is still confusing.
- (them) Do a couple of homework problems. Before the next meeting, for full credit; before the following meeting, for partial credit.

As you can tell, this is a lot of work for everyone, and—by design—it’s not flexible. To compensate, I won’t give exams. There will be some group projects for summative assessments instead.