---
title: 'Data science? Data science!'
date: 2015-07-30
author: "Toby Driscoll"
categories:
  - academia
  - math
  - teaching
---



I just received a copy of [SIAM News](http://sinews.siam.org/) on a dead tree. It features [a piece](http://sinews.siam.org/DetailsPage/tabid/607/ArticleID/565/Data-Science.aspx) by [Chris Johnson](https://www.cs.utah.edu/~crj/) and [Hans de Sterck](http://math.uwaterloo.ca/amath-numerical-analysis-and-scientific-computing-group/hans-de-stercks-homepage) about "Data Science: What Is It and How Is It Taught?" As usual in these articles, I find the specifics more interesting than the generalities of a panel discussion. I really liked this bit about the new program in [Computational Modeling and Data Analytics at Virginia Tech](http://www.science.vt.edu/ais/cmda/):


  
>    In a sense, creating such a program offers the opportunity to rethink curricula on classical topics like calculus that have at many institutions not seen substantial change throughout most of the past century.


This! Well outside the context of data science, too.



I'm so sick of teaching calculus as though it were still 1960. Not that calculus has changed, of course, but what we need from it has been utterly transformed. In the age of computing, knowledge of calculus is more useful for posing the right questions---as opposed to getting answers to mindless exercises that can be done in seconds on [Wolfram Alpha](http://wolframalpha.com). Don't even get me started on teaching series convergence tests to engineering freshmen.



As far as how to teach data science...let me figure out how to learn it, first. I'm intrigued by [this repository](https://github.com/okulbilisim/awesome-datascience) as a start.
