---
title: "The sorry state of teaching ODEs"
author: "Toby Driscoll"
categories:
  - teaching
date: 2019-07-16T11:55:12-04:00
---
I've spent the last two spring semesters teaching ODEs (ordinary differential equations) to a total of about 170 biomedical and chemical engineering majors. The content is dictated by a number of constraints: the perceived desires of the client departments, multiple instructors, all of whom have more experience with the course than I do, and traditional expectations. Based on a limited survey of popular textbooks ([this](https://www.amazon.com/Differential-Equations-Engineers-David-Kalbaugh/dp/1498798810), [this](https://www.amazon.com/Engineering-Differential-Equations-Theory-Applications/dp/1441979182), and our choice, [Brannan and Boyce](https://www.amazon.com/Differential-Equations-Introduction-Methods-Applications/dp/1118531779)), many courses like this are quite similar. (You can look through my [notes](https://tobydriscoll.net/udmath305/notes.html), rough as they are.)

What I find particularly disheartening about these books, and the courses they imply, is that they share an overwhelming emphasis on hand computations of formulas to produce "solutions" of particular problems. I scare-quote "solutions" here because it's become clear that the majority of students can't readily comprehend their own outputs. And really, why should they? Most homework (and, by implication, exam) problems are going to simply ask them to produce the output, not interpret it. 

Not long ago, this approach was not hard to justify. What could be more important to building a bridge or [going to the Moon](https://www.bbc.co.uk/programmes/w13xttx2) than getting the right answer? Of course it's absurd to suggest that getting the right answer no longer matters. But what *does* no longer matter is whether the student can crank that answer out by hand. 

I'm old enough to remember a middle school lecture on finding values of logarithms by linearly interpolating values from a table. I sincerely hope this is no longer done, though I can imagine the objections when it was proposed for elimination: "Isn't it good for them to learn linear interpolation? What if they're stuck on a desert island without a calculator? How will they recognize when the calculator gives a clearly wrong answer?" You'll hear much the same said about many other dubious lessons that are still very much alive today, such as days of calculus devoted to drawing (bad) graphs by hand. 

Long after the original driving need to compute or do something by hand has vanished, we're able to supply alternative reasons to do it. These reasons seem to come in two flavors: hypothetical utility and tradition. Claims that students "learn concepts better" by hand computing are almost never substantiated by evidence, and in any case tend to beg the question of which concepts are in play. I think we can conclusively retire the "they may not always have a calculator" form of manufactured need. As for grimly continuing a tradition, sometimes disguised within a beguiling "what's the harm?" phrasing, what you get is a recipe for stagnation and irrelevance. The cost is always a lost opportunity to teach something else.  

I would not suggest that students never solve an example problem by hand. An ODE course graduate who cannot solve, say, $y^{\prime\prime} + 4y=1$ has missed something vital. But I don't see what's to be gained by practicing on $y^{\prime\prime} + 5y' + 4y=t^2e^{-2t}$. All the time and focus needed to wrest an answer from that problem is purely mechanical, never going beyond the application of a rigid algorithm. 

Not only are such algorithms much better performed by a computer, they are incredibly fragile. The [analytical solution](https://www.wolframalpha.com/input/?i=solve+y%27%27+%2B+t*y+%3D+1) of $y^{\prime\prime} + ty=1$ is *so much* harder to produce and interpret than $y^{\prime\prime} + 4y=1$ that it might as well be of a different universe altogether. And that's still just a linear problem! 

It's sensible to focus on the most fundamental ODE problems with analytical solutions, like the linearly damped oscillator and the logistic equation. We can totally dissect those problems, and they represent the simplest form of more complicated and realistic models. But when we give the impression that analytical solutions are the primary objective of the ODE world, we grossly distort the true picture. Already when I was a graduate student over 25 years ago, there were [great computational ODE tools](https://dsweb.siam.org/Software/dstool) that would give you a fast and detailed understanding of dynamics. If you were inclined and able, you might go on to make some exact analytical (qualitative) conclusions suggested by the numerical and graphical explorations. But that's a pursuit for a modestly sized cadre of mathematically advanced academics. It's not the use case for over 99% of our undergraduates taking their one lifetime ODE course. 

Rather than trying to turn our students into slow and error-prone Mathematica simulators, we ought to be equipping our students with ODE fluency. Modeling, nondimensionalization, stability, and resonance are all more fundamental and vital than knowing [every last case of the method of undetermined coefficients](http://tutorial.math.lamar.edu/Classes/DE/UndeterminedCoefficients.aspx). Knowing the stability implications of poles in a [transfer function](https://en.wikipedia.org/wiki/Transfer_function) is more important than performing partial fraction decompositions to invert Laplace transforms by hand. 

What's a more relevant use of time: solving artificial scalar problems carefully selected to have compact analytical solutions, or learning how to simulate [ODE models of beer fermentation](https://onlinelibrary.wiley.com/doi/abs/10.1002/j.2050-0416.1994.tb00830.x) or [passive walking down a ramp](https://www.ncbi.nlm.nih.gov/pubmed/10412391)? 

Someday, perhaps, I will get to teach an ODE course that follows the [textbook I co-authored with Trefethen and Birkisson](/project/explode/). We used [Chebfun](http://www.chebfun.org) to do the heavy lifting of solving problems and discussed at length how to read an ODE and investigate its behavior thoroughly. By not dwelling on now-archaic analytical solution methods, we were able to include introductions to chaos, stochastics, eigenvalues, bifurcations, and boundary layers, all essential phenomena that never make it into a traditional class. 

Until that happy day arrives, I guess you can find me trying to motivate 70 engineers to learn how to compute the exponential of 2-by-2 matrices. 

