---
title: 'Promotion system'
description: "Can mastery-based learning work in a college math course?"
date: 2015-07-17
author: "Toby Driscoll"
categories:
  - teaching
---



  In keeping with my post on [how grades in a course affect student motivation](../grades-and-motivation/index.qmd), I've been pondering alternatives to the classic mean-them-and-mean-it model.



  All of my family members have spent time studying karate. (I'm a brown belt, FYI, which is like an A.B.D.) One thing I've always liked about the dojos I've known is how the belt promotion system works. It's what I would now call a [mastery based learning](http://www.knewton.com/blog/ed-tech-101/edtech-101-mastery-based-learning/) concept. Students are tested to advance to the next belt when they are ready, regardless of time spent in the system (of course there are practical limitations on the speed of progression). The tests themselves are rigorous but the results are typically foregone conclusions, by design.



  Truly self-paced mastery learning is difficult to fit into the college grading model. With a technology assist it's possible in topics like pre-calculus and at least some calculus, and probably a few other introductory courses I'm not familiar with. I don't see how I could do it in my advanced course this fall.



  I could also think of a more corporate model, which is where most of the students will end up. So the first few weeks would be like an interview to determine the initial job rank (i.e., final grade). Based on performance I would give personal feedback and update their ranks accordingly throughout the term. This goes hand in hand with [continuous assessment](../making-continuous-assessment-work/index.qmd), which I plan to do anyway.



  Because the later material in part builds on earlier concepts, I could argue that progress later on could make up for early struggles. In any case students would be free to fight for grade promotions to the very end of the course. Unlike the karate model, demotions are possible, so they couldn't reach an acceptable level and just lay back.



  A radical realization of this concept would include doing away with the numerical grades on each assignment! I admit, that excites me---I can't stand the arbitrariness of deciding how many "points" each mistake is worth. I see no reason why a [grading rubric](https://www.cmu.edu/teaching/designteach/teach/rubrics.html) can't be precise without being applied quantitively.



  This would be a huge culture shift for me and for the students. It's risky. I'd love to hear opinions and experiences trying to do this sort of thing in math.

