---
title: 'It already has happened here'
date: 2016-12-18T15:28:34+00:00
author: "Toby Driscoll"
categories:
  - society and culture
---



I've just finished one of the most remarkable fiction reading experiences I've had in quite some time: [*It Can't Happen Here*](https://en.wikipedia.org/wiki/It_Can%27t_Happen_Here), by [Sinclair Lewis](https://en.wikipedia.org/wiki/Sinclair_Lewis).



*ICHH* is a satirical novel written and set in 1935 America. It describes the rise of a populist dictatorship modeled closely along the rise of the Nazis in Germany.(Lewis' wife, [Dorothy Thompson](https://en.wikipedia.org/wiki/Dorothy_Thompson), was the first American journalist expelled from Nazi Germany and was clearly responsible for much of the shape of the book.)



This was near the height of the Depression, and FDR's New Deal was controversial and, at that point unsuccessful (or not yet successful, if you want to look at it that way). There were multiple signs of unrest and populism, not least of which was [Huey Long](https://en.wikipedia.org/wiki/Huey_Long), then governor of Louisiana and apparently plotting to hijack the Democratic party to get elected President in 1936 or 1940. (Long was assassinated in 1935, as the book was being finished.)



*ICHH* is not great as a novel. The characters are essentially allegorical, and the plot barely needs them. The core of the book is as a dystopian speculation about the near future of the USA. Lewis himself called it "propaganda for American democracy." As such, its relevance to 2016 is astonishing. I could pick out dozens of quotes. Here are just three extended ones.

  
>  ...what burns me up [isn't] that old soap-boxer's old chestnut about how one tenth of one percent of the population at the top have an aggregate income equal to 42 percent at the bottom....[It's] the fact that even before this Depression, in what you folks called prosperous times, 7 per cent of all the families in the country earned $500 a year or less---remember, those weren't the unemployed, on relief; those were the guys that still had the honor of doing honest labor.
  
  
  
>  The most confusing thing about the campaign of 1936 was the relationship of the two leading parties. Old-Guard Republicans were complaining that their proud party was begging for office, hat in hand; veteran Democrats that their traditional Covered Wagons were jammed with college professors, city slickers, and yachtsmen.
  
  
  
>  Most Americans had learned in school that God had supplanted the Jews as chosen people by the Americans, and this time done the job much better, so that we were the richest, kindest, and cleverest nation living; that depressions were but passing headaches and that labor unions...must not set up an ugly class struggle by combining politically; that, though foreigners tried to make a bogus mystery of them, politics were really so simple that any village attorney or any clerk in the office of a metropolitan sheriff was quite adequately trained for them; and that if John D. Rockefeller or Henry Ford had set his mind to it, he could have become the most distinguished statesman, composer, physicist, or poet in the land.
  

So much is in the book: the rural/urban dynamic, the American disdain for and distrust of intellectualism, the cluelessness of intellectuals, racism, anti-Semitism, antifeminism, the lust for a "ringmaster-revolutionist", the contrast between a boring, calculating candidate and a hot populist who draws big rallies, the failure of newspapers (i.e. the media in 1935), the use of radio for disintermediation (i.e., Twitter), the belief by the banking establishment that things would soon moderate and work in their favor, etc. Lewis also spells out the horrors of a concentration camp---familiar ground to us today, but sensational to much of the public in 1935.



In 1935 the bogeyman was communism, not Islam, and the threat seems to be the extreme left, not the right. But that hardly matters. What *ICHH* made so clear to me is how America, through its history, culture, and politics, is a host susceptible to a certain pattern of symptoms. And maybe it's not just America, and not just liberal democracy, but literally part of our DNA.



I'm quickly going over in my head in political science here. My reaction to the book is complicated. I recommend that you pick up a copy and at least get through the fictional election, though it's neither easy nor fun to read.



The book was apparently adapted to a smash hit play in 1937. I would be surprised if it doesn't undergo a revival in the near future.

