---
title: 'Grades and motivation'
description: "What even is a grade, anyway?"
date: 2015-07-14
author: "Toby Driscoll"
categories:
  - teaching
---

  Grading is weird in so many ways. In the U.S. system, we report a "letter" grade that is basically an integer from 0 to 10 or so. This value appears on the student's transcript without comment or context, which is an inherently meaningless way to present any data.

  But the raw value itself isn't well defined anyway. When I give a student a C+ in calculus, does it mean that she mastered about 75% of the major topics in the course? Or does it mean that she understands about 3/4 of what is going on in any particular topic? Which of these is preferable? Would a C+ in bicycle riding be enough of a prerequisite to learn how to ride a motorcycle?

  The closest analog to grades in the real world that I can think of is the annual or quarterly performance review. There are doubts being expressed about these too. In [a piece on Bloomberg Business](http://www.bloomberg.com/bw/articles/2013-11-07/the-annual-performance-review-worthless-corporate-ritual), long-time management consultant Aubrey Daniels says, "It’s a sadistic process for what purpose I don’t know....Think of a sports team: A coach doesn’t wait until the end of a season to give his players feedback." So, we're coming back around to [continuous assessment](http://tobydriscoll.net/blog/blog/2015/07/13/making-continuous-assessment-work/).

  Yet the *form* of the assessment needs to change too.

  What motivates people in the workplace? For one thing, being recognized for their successes. In math we tend to view perfection as the standard, and everything that falls short on homework or exams earns deductions. This is a notably dismal and discouraging viewpoint for learners. It emphasizes the negativity of errors both large and small. When you compare the (hopefully!) flawless and polished solutions on the answer key with your own stumbling attempts, how could you feel anything but foolish? Where is the upside?

  Another thing that motivates us in the real world is a chance to fix our failures. If you've scored badly on two midterms in a calculus course, you're probably wise to invest your effort elsewhere. The chances of pulling yourself out of the muck are small, in part because averages are heartless and have perfect memory. I always have disdained grading methods that forgive early bad scores or give "extra" credit chances, but I have to admit that a system that makes recovery from a bad start seem impossible is no way to maintain motivation.

  I don't have answers yet, but I'm thinking about some things. More later.

